apiVersion: v1
kind: Service
metadata:
  name: boilerplay
  labels:
    app: boilerplay
spec:
  ports:
  - port: 80
    targetPort: 9000
    name: http
  selector:
    app: boilerplay
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boilerplay
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: boilerplay
    spec:
      containers:
      - name: app
        image: boilerplay:latest
        ports:
        - containerPort: 9000
